spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://192.168.1.207:3306/datadire?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.207:3306/datadire?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      filter:
        config:
          enabled: true
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
      stat-view-servlet:         #开启web监控页面
        url-pattern: /druid/*  #web访问路径
        allow: localhost       #允许访问的ip,不配置默认所有地址都可以访问
        login-username: admin  #访问需要的用户名
        login-password: 123654 #访问需要的密码
        enabled: true
      web-stat-filter:    #配置web过滤器
        url-pattern: /*   #过滤url
        #exclusions: /druid/*  #排除过滤
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        enabled: true
        profile-enable: true  #监控单个url调用的sql列表
      #connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKaWNv8bdl0VzRZDhspOazg+EtCqR3+2LnlllxSG2QtALDDSTeuHuf+jSyrNAXcwMV0suIvWLlkjBhWzC0Gab6sCAwEAAQ==
      filters: stat,wall
ribbon:
  ReadTimeout : 5000
  ConnectTimeout : 5000