server:
  port: 30108
  servlet:
    context-path: /catalog
    session:
      timeout: PT5H
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      max-active: 500
      initial-size: 2
      max-wait: 60000
      min-idle: 2
  thymeleaf:
    cache: false
    suffix: .html
    encodint: utf-8
    mode: HTML
    servlet:
      content-type: text/html
http:
  maxTotal: 400
  defaultMaxPerRoute: 100
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
    